### ISSUE TITLE
What is the license for php-noise.com?

### ISSUE THREAD

**Issue by Griefed** [RundesBalli/php-noise.com#1]
Hello RundesBalli,

I'm curious which license you would apply for php-noise.com as I am interested in including it in my [App-Collection](https://github.com/Griefed/docker-App-Collection) docker container. An example of said container can be viewed at https://apps.griefed.de.
I would like the noise generator website/ui to be available at https://apps.griefed.de/noise, or if someone else uses said container, at http(s)://subdomain.domain.tld/noise.

Currently, the random generator can be previewed at /noise of said website, as your random generator uses the MIT License.

I would like to hear your thoughts on this.

Cheers,
Griefed

**Comment by RundesBalli** [comment]
Hi!

Feel free to use the website in your Docker container. As license model I would choose [the same license as in the generator repository](https://github.com/RundesBalli/php-noise/blob/master/LICENSE), MIT, **with the exception** that the imprint link in the footer must be removed, since I am not the operator of every copy of your Docker container.

Change the line https://github.com/RundesBalli/php-noise.com/blob/db891e9f8c30abb3a084a2808dd56cda75f205c2/public/index.html#L66 to the following:
```html
      A project by: <a href="https://rundesballi.com/" target="_blank" rel="noopener">RundesBalli.com</a><a href="https://github.com/RundesBalli/php-noise" target="_blank" rel="noopener">GitHub</a>
```
Thanks for using my software!

Greetings,
RB

**Comment by RundesBalli** [comment]
I created a [LICENSE.md](https://github.com/RundesBalli/php-noise.com/blob/master/LICENSE.md) which refers to this comment.
